/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Salomon' at '3/24/16 10:30 PM' with Gradle 2.9
 *
 * @author Salomon, @date 3/24/16 10:30 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
