import static org.junit.Assert.*;

import org.junit.Test;

import Fixtures.Addresses;
import Fixtures.Customers;
import Fixtures.Tickets;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Salomon' at '3/24/16 10:30 PM' with Gradle 2.9
 *
 * @author Salomon, @date 3/24/16 10:30 PM
 */
public class DALTest {
    @Test public void testFixtures() {
    	assertEquals(Customers.cust0.getAddress().getId(), Addresses.add0.getId());
    }
    @Test public void testSynopsis() {
    	assertEquals(Customers.cust0.synopsis(),"Smeke, Salomon: 8135023883. Active?: true. Batman Str, #0 60660");
    }
    @Test public void diagnoseTicket() {
    	assertEquals(true,Tickets.ti0.verify());
    }
}
