import static org.junit.Assert.*;

import org.junit.Test;

import Fixtures.Addresses;
import Fixtures.Customers;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Salomon' at '3/24/16 10:30 PM' with Gradle 2.9
 *
 * @author Salomon, @date 3/24/16 10:30 PM
 */
public class DALTest {
    @Test public void testSomeLibraryMethod() {
    	assertEquals(Customers.cust0.getAddress(), Addresses.add0.getId());
    }
}
