import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Salomon' at '3/24/16 10:30 PM' with Gradle 2.9
 *
 * @author Salomon, @date 3/24/16 10:30 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    }
}
